name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Echo Go version
        run: (go version)

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run tests
        run: (go test ./... --cover)

      - name: Run security check
        run: gosec ./...
  style:
      name: Style
      runs-on: ubuntu-latest

      steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.22'

        - name: Install staticcheck
          run: go install honnef.co/go/tools/cmd/staticcheck@latest

        - name: Run style check
          run: (test -z $(go fmt ./...))

        - name: Run linting
          run: staticcheck ./...

